name: web_kit_plugin
description: "A new Flutter FFI plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0-149.0.dev <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen:
    path:
      ../native/pkgs/ffigen
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
        pluginClass: WebKitPlugin
